blogs/urls.py
from django.urls import path
from blogs.apps import BlogsConfig
from blogs.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdatelView, ArticleDeleteView

app_name = BlogsConfig.name
urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ArticleUpdatelView.as_view(), name='edit'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emailservice.urls', namespace='imailservice')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

emailservice/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from emailservice.apps import EmailserviceConfig
from emailservice.views import EmailservicePageView, EmailserviceListView, MailingCreateView, MailingUpdateView, \
    MailingDetailView, MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    ClientDetailView, LogListView

app_name = EmailserviceConfig.name

urlpatterns = [
    path('', EmailservicePageView.as_view(), name='home'),
    path('lk', EmailserviceListView.as_view(), name='lk'),
    path('create/<int:pk>/', MailingCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', MailingUpdateView.as_view(), name='edit'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('delete/<int:pk>/', cache_page(60)(MailingDeleteView.as_view()), name='delete'),
    path('client_list', ClientListView.as_view(), name='client_list'),
    path('create_client/<int:pk>/', ClientCreateView.as_view(), name='create_client'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_edit/<int:pk>/', ClientUpdateView.as_view(), name='client_edit'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('logs_list/', LogListView.as_view(), name='logs_list'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    email_verification,
    PasswordResetView,
    UserListView,
    UserUpdateView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("email-confirm/<str:token>/", email_verification, name="email_verification"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    path("users/", UserListView.as_view(), name="user_list"),
    path("user/edit/<int:pk>", UserUpdateView.as_view(), name="user_update"),
]

emailservice/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Client(models.Model):
    name = models.CharField(max_length=35, verbose_name="name")
    last_name = models.CharField(max_length=35, verbose_name="last_name", **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='email')
    comment = models.TextField(verbose_name='comment', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name="client")

    def __str__(self):
        return f" {self.name} {self.email}"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"


class Mailing(models.Model):
    DAY = 'ежедневно'
    WEEK = 'раз в неделю'
    MONTH = 'раз в месяц'
    CREATE = 'создана'
    START = 'запущена'
    STOP = 'завершена'
    CHOICE_PERIOD = [
        (DAY, "Раз в день"),
        (WEEK, "Раз в неделю"),
        (MONTH, "Раз в месяц"),
    ]
    CHOICE_STATUS = [
        (STOP, "Завершена"),
        (CREATE, "Создана"),
        (START, "Запущена"),
    ]

    name = models.CharField(max_length=50, verbose_name="Тема рассылки")
    message = models.TextField(verbose_name="Сообщение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создана")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Изменена")
    clients = models.ManyToManyField(Client, related_name="clients", verbose_name="Клиенты")
    start_mail = models.DateTimeField(default=timezone.now, verbose_name="Начало рассылки")
    stop_mail = models.DateTimeField(default=(timezone.now() + timezone.timedelta(days=1)),
                                     verbose_name="Конец рассылки")
    period_mail = models.CharField(
        max_length=100,
        choices=CHOICE_PERIOD,
        default=DAY,
        verbose_name="Периодичность")
    status_mail = models.CharField(max_length=100, choices=CHOICE_STATUS, default=CREATE, verbose_name="Статус")
    next_send_time = models.DateTimeField(verbose_name='Время следующей отправки', **NULLABLE)
    last_send_at = models.DateTimeField(null=True, verbose_name="Последняя рассылка")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"{self.name} ({self.last_send_at}) {self.owner}"

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Log(models.Model):
    SUCCESS = 'Успешно'
    FAIL = 'Неуспешно'
    STATUS_VARIANTS = [
        (SUCCESS, 'Успешно'),
        (FAIL, 'Неуспешно'),
    ]

    time = models.DateTimeField(
        verbose_name="Дата и время попытки отправки", auto_now_add=True
    )
    status = models.CharField(max_length=50, choices=STATUS_VARIANTS, verbose_name='Cтатус рассылки')
    server_response = models.CharField(
        max_length=150, verbose_name="Ответ сервера почтового сервиса", **NULLABLE
    )
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Рассылка")

    def __str__(self):
        return f"{self.mailing} {self.time} {self.status} {self.server_response}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

emailservice/forms.py
from django.forms import ModelForm

from emailservice.models import Mailing, Client


class MailingForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(owner=self.request.user)

    class Meta:
        model = Mailing
        fields = ('name', 'message', 'clients', 'period_mail', 'start_mail', 'stop_mail', 'next_send_time')


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'last_name', 'email', 'comment')

emailservice/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView

from blogs.services import get_articles_from_cache
from emailservice.forms import MailingForm, ClientForm
from emailservice.models import Mailing, Client, Log
from emailservice.services import get_mailings_from_cache
from users.models import User


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('emailservice:client_list')

    def form_valid(self, form):
        client_form = form.save()
        user = self.request.user
        client_form.owner = user
        client_form.save()
        return super().form_valid(form)


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client
    template_name = 'emailservice/client_detail.html'


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('emailservice:client_list')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('emailservice:client_list')


class EmailservicePageView(TemplateView):
    template_name = 'emailservice/start.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blogs'] = get_articles_from_cache().order_by('?')[:3]
        return context_data


class EmailserviceListView(ListView):
    model = Mailing
    template_name = 'emailservice/lk.html'

    def get_queryset(self):
        return get_mailings_from_cache()


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('emailservice:lk')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('emailservice:lk')


class MailingDetailView(DetailView):
    model = Mailing


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('emailservice:lk')


class LogListView(LoginRequiredMixin, ListView):
    model = Log

emailservice/templates/emailservice/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Starter Template · Bootstrap v5.0</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>


    <!-- Custom styles for this template -->

</head>
<body>

<div class="container py-3">
    <header>
        {% include 'emailservice/includes/inc_menu.html' %}
    </header>

    <div class="col-lg-8 mx-auto p-3 py-md-5">


        <main>
            <h1>Добро пожаловать в Почтовую службу</h1>
            <p class="fs-5 col-md-8">Лучшее решение для оповещения ваших клиентов.</p>


            {% block content %}
            {% endblock%}

        </main>
    </div>
</div>


<script src="{%static 'js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

emailservice/templates/emailservice/client_confirm_delete.html
{% extends 'emailservice/base.html'%}
{% block content %}
<div class="conteiner">
    <div class="row">
        <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" >
                        {% csrf_token %}
                               <p> Удалить клиента ?"{{ client.email }}"</p>
                               <button type="submit" class="btn btn-danger">Удалить</button>
                               <a href="{% url 'emailservice:client_detail' client.pk %}" class="btn btn-success">Отмена</a>
                        </form>
                </div>
        </div>
    </div>
</div>
{% endblock %}
</div>

emailservice/templates/emailservice/client_detail.html
{% extends 'emailservice/base.html'%}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">Имя: {{ client.name }}</p>
                    <p class="card-text">Фамилия: {{ client.last_name }}</p>
                    <p class="card-text">email: {{ client.email }}</p>
                    <p class="card-text">Комментарий: {{ client.comment }}</p>
                    <p class="card-text">Владелец: {{ client.owner }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'emailservice:client_edit' client.pk %}" type="button"
                               class="btn btn-sm btn-block btn-outline-primary">Редактировать</a>
                            <a href="{% url 'emailservice:client_delete' client.pk %}" type="button"
                               class="btn btn-sm btn-block btn-outline-danger">Удалить</a>
                        </div>
                        <small class="text-body-secondary"></small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailservice/templates/emailservice/client_form.html
{% extends 'emailservice/base.html'%}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="conteiner">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-titel">
                            Добавить клиента
                        </h3>
                        <div class="card-body">
                            {% csrf_token %}
                            <input type="hidden" name="user" value="{{ user.pk }}">
                            {{ form.as_p}}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                        </button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>>
{% endblock %}

emailservice/templates/emailservice/client_list.html
{% extends 'emailservice/base.html'%}
{% block content %}

<hr class="col-3 col-md-2 mb-5">

<div class="row g-5">
    <div class="col-md-12">
        <h2>Список клиентов</h2>
        <a href="{% url 'emailservice:create_client' user.pk %}" class="btn btn-primary my-2">Добавить клиента</a>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">imail</th>
                <th scope="col">ККоментарий</th>
                <th scope="col">Действие</th>
            </tr>
            </thead>

            {% for client in object_list %}
            {% if user == client.owner %}
            <tbody>
            <tr>
                <th scope="row">{{client.id}}</th>
                <td>{{ client.name }}</td>
                <td>{{ client.last_name }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.comment }}</td>
                <td><a href="{% url 'emailservice:client_detail' client.pk %}">Открыть</a></td>
            </tr>
            </tbody>
            {% endif %}
            {% endfor %}
        </table>
        <ul class="icon-list">
            <li><a href="https://github.com/twbs/bootstrap-npm-starter" rel="noopener" target="_blank">Bootstrap npm
                starter</a></li>
            <li class="text-muted">Bootstrap Parcel starter (coming soon!)</li>
        </ul>
    </div>

    <div class="col-md-6">
        <h2>Guides</h2>
        <p>Read more detailed instructions and documentation on using or contributing to Bootstrap.</p>
        <ul class="icon-list">
            <li><a href="/docs/5.0/getting-started/introduction/">Bootstrap quick start guide</a></li>
            <li><a href="/docs/5.0/getting-started/webpack/">Bootstrap Webpack guide</a></li>
            <li><a href="/docs/5.0/getting-started/parcel/">Bootstrap Parcel guide</a></li>
            <li><a href="/docs/5.0/getting-started/build-tools/">Contributing to Bootstrap</a></li>
        </ul>
    </div>
</div>

{% endblock %}

emailservice/templates/emailservice/lk.html
{% extends 'emailservice/base.html'%}
{% block content %}
{% load m_filter %}
<hr class="col-3 col-md-2 mb-5">

<div class="row g-5">
    <div class="col-md-12">
        <h2>Список ваших рассылок</h2>
        <a href="{% url 'emailservice:create' user.pk %}" class="btn btn-primary my-2">Создать новую рассылку</a>
        <a href="{% url 'emailservice:client_list' %}" class="btn btn-primary my-2">Список клиентов</a>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Тема</th>
                <th scope="col">Создана</th>
                <th scope="col">Посдедняя отправка</th>
                <th scope="col">Статус</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>

            {% for mailing in object_list %}
            {% if user == mailing.owner or user.is_staff %}
            <tbody>
            <tr>
                <th scope="row">{{mailing.id}}</th>
                <td>{{ mailing.name }}</td>
                <td>{{ mailing.created_at }}</td>
                <td>{{ mailing.last_send_at }}</td>
                <td>{{ mailing.status_mail }}</td>
                <td><a href="{% url 'emailservice:mailing_detail' mailing.pk %}">открыть</a></td>
            </tr>
            </tbody>
            {% endif %}
            {% endfor %}
        </table>

    </div>

    <div class="col-md-6">
        <h2>Guides</h2>
        <p>Read more detailed instructions and documentation on using or contributing to Bootstrap.</p>
        <ul class="icon-list">
            <li><a href="/docs/5.0/getting-started/introduction/">Bootstrap quick start guide</a></li>
            <li><a href="/docs/5.0/getting-started/webpack/">Bootstrap Webpack guide</a></li>
            <li><a href="/docs/5.0/getting-started/parcel/">Bootstrap Parcel guide</a></li>
            <li><a href="/docs/5.0/getting-started/build-tools/">Contributing to Bootstrap</a></li>
        </ul>
    </div>
</div>


{% endblock %}

emailservice/templates/emailservice/log_list.html
{% extends 'emailservice/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Попытки рассылок</h1>
    </div>
</section>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Рассылка</th>
        <th scope="col">Время</th>
        <th scope="col">Статус</th>
        <th scope="col">Ответ сервера</th>
    </tr>
    </thead>
    <tbody>
    {% for log in object_list %}

    <tr>
        <td>{{ log.mailing }}</td>
        <td>{{ log.time }}</td>
        <td>{{ log.status }}</td>
        <td>{{ log.server_response }}</td>
    </tr>

    {% endfor %}
    </tbody>
</table>
{% endblock %}

emailservice/templates/emailservice/mailing_confirm_delete.html
{% extends 'emailservice/base.html'%}
{% block content %}
<div class="conteiner">
    <div class="row">
        <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" >
                        {% csrf_token %}
                               <p> Удалить рассылку ?"{{ mailing.name }}"</p>
                               <button type="submit" class="btn btn-danger">Удалить</button>
                               <a href="{% url 'emailservice:mailing_detail' mailing.pk %}" class="btn btn-success">Отмена</a>
                        </form>
                </div>
        </div>
    </div>
</div>
{% endblock %}
</div>

emailservice/templates/emailservice/mailing_detail.html
{% extends 'emailservice/base.html'%}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">Тема: {{ mailing.name }}</p>
              <p class="card-text">Сообщение: {{ mailing.message }}</p>

              <p class="card-text">Клиенты: {{ mailing.clients.all }}</p>
              <p class="card-text">Владелец: {{ mailing.owner }}</p>
              <div class="d-flex justify-content-between align-items-center">
                {% if  user == mailing.owner %}
                <div class="btn-group">
                  <a href="{% url 'emailservice:edit' mailing.pk %}" type="button" class="btn btn-sm btn-block btn-outline-primary">Редактировать</a>
                  <a href="{% url 'emailservice:delete' mailing.pk %}" type="button" class="btn btn-sm btn-block btn-outline-danger">Удалить</a>
                </div>
                {% endif %}

                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

emailservice/templates/emailservice/mailing_form.html
{% extends 'emailservice/base.html'%}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="conteiner">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-titel">
                            Саздать рассылку
                        </h3>
                        <div class="card-body">
                            {% csrf_token %}
                            <input type="hidden" name="user" value="{{ user.pk }}">
                            {{ form.as_p}}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                        </button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>>
{% endblock %}

emailservice/templates/emailservice/start.html
{% load static %}
{% load m_filter %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Email service</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/jumbotron/">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <script type="text/javascript"
            src="https://me.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=_pRBsL3lr1aFNc8R0IwptgpILJxKgMwNeizElgusjj72fKX7VQMTjAy46gkRRb93eidaf1pjaRYNbK16imZ3gQlebU1vIlD3ZG3zQb3A-RA"
            charset="UTF-8"></script>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>


</head>
<body>

<main>
    <div class="container py-4">
        <header class="pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94"
                     role="img"><title>Bootstrap</title>
                    <path fill-rule="evenodd" clip-rule="evenodd"
                          d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                          fill="currentColor"></path>
                </svg>

            </a>
        </header>

        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Почтовая служба </h1>
                <p class="col-md-8 fs-4">Сайт рассылки электонных писем. Чтобы воспользоваться услугами сайта, вам
                    Необходимо войти или зарегистрироваться.</p>
                <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Вход</a>
                <a href="{% url 'users:register' %}" class="btn btn-primary my-2">Регистрация</a>
            </div>
        </div>

        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Блоги</h1>
                    <p>
                        <a href="{% url 'blogs:list' %}" class="btn btn-primary my-2">Посмотреть все блоги</a>
                    </p>
                </div>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">
                {% for object in blogs %}
                <div class="col-4">
                    <div class="card shadow-sm">
                        <img src="{{ object.image | media_filter }}">
                        <div class="card-body">
                            <p class="card-text">
                            <h2>{{ object.name}}</h2>
                            <p class="card-text">Содержание: {{ object.descriptiony }}</p>
                            <p class="card-text"> Создана {{ object.created_at }}</p>
                            <p class="card-text">Просмотры- {{ object.caunt_views }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

</body>
</html>