blogs/urls.py
from django.urls import path
from blogs.apps import BlogsConfig
from blogs.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdatelView, ArticleDeleteView

app_name = BlogsConfig.name
urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ArticleUpdatelView.as_view(), name='edit'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emailservice.urls', namespace='imailservice')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Article(models.Model):
    name = models.CharField(max_length=100, verbose_name="заголовок")
    description = models.TextField(verbose_name="содержимое")
    image = models.ImageField(
        upload_to="image/", verbose_name="изображение", **NULLABLE
    )
    created_at = models.DateField(verbose_name="дата создания")
    count_views = models.IntegerField(default=0, verbose_name="просмотры")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ("name",)

blogs/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blogs.models import Article
from blogs.services import get_articles_from_cache


class ArticleCreateView(CreateView):
    model = Article
    fields = ('name', 'description', 'image', 'created_at')
    success_url = reverse_lazy('blogs:list')


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        return get_articles_from_cache()


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.caunt_views += 1
        self.object.save()
        return self.object


class ArticleUpdatelView(UpdateView):
    model = Article
    fields = ('name', 'description', 'image', 'created_at')

    def get_success_url(self):
        return reverse('blogs:view', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blogs:list')

blogs/templates/blogs/article_confirm_delete.html
{% extends 'emailservice/base.html'%}
{% block content %}
<div class="conteiner">
    <div class="row">
        <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" >
                        {% csrf_token %}
                               <p> Удалить блог?"{{ article.name }}"</p>
                               <button type="submit" class="btn btn-danger">Удалить</button>
                               <a href="{% url 'blogs:list' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/article_detail.html
{% extends 'emailservice/base.html'%}
{% load m_filter %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ article.image | media_filter }}">
            <div class="card-body">
              <p class="card-text">Заголовок: {{ article.name }}</p>
              <p class="card-text">Содержание: {{ article.description }}</p>
              <p class="card-text">Просмотров: {{ article.count_views }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blogs:list' %}" role="button">Назад</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/article_form.html
{% extends 'emailservice/base.html'%}
{% block content %}
<div class="conteiner">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-prymary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать</button>
                        {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/article_list.html
{% extends 'emailservice/base.html'%}
{% load m_filter %}
{% block content %}
<body>
<section class=" text-center container">
    <div>
        <p>
            <a href="{% url 'blogs:create' %}" class="btn btn-primary my-2">Добавить блог</a>
        </p>
        <a href="{% url 'emailservice:home' %}" class="btn btn-primary my-2">Главная</a>
    </div>
</section>


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список блогов</h1>
</div>
<div class="container">
    <div class="row text-center">
        {% for article in object_list %}
        <div class="col-5">
            <div class="card mb-4 box-shadow">
                <img src="{{ article.image | media_filter }}">
                <div class="card-body">
                    <p class="card-text">Заголовок: {{ article.name }}</p>
                    <p class="card-text">Содержание: {{ article.description }}</p>
                    <p class="card-text">Просмотров: {{ article.count_views }}</p>

                    <a href="{% url 'blogs:view' article.pk %}" type="button"
                       class="btn btn-sm btn-block btn-outline-primary">Открыть</a>
                    <a href="{% url 'blogs:edit' article.pk %}" type="button"
                       class="btn btn-sm btn-block btn-outline-primary">Изменить</a>
                    <a href="{% url 'blogs:delete' article.pk %}" type="button"
                       class="btn btn-sm btn-block btn-outline-danger">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>
{% endblock %}