blogs/urls.py
from django.urls import path
from blogs.apps import BlogsConfig
from blogs.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdatelView, ArticleDeleteView

app_name = BlogsConfig.name
urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ArticleUpdatelView.as_view(), name='edit'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emailservice.urls', namespace='imailservice')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    email_verification,
    PasswordResetView,
    UserListView,
    UserUpdateView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("email-confirm/<str:token>/", email_verification, name="email_verification"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    path("users/", UserListView.as_view(), name="user_list"),
    path("user/edit/<int:pk>", UserUpdateView.as_view(), name="user_update"),
]

emailservice/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Client(models.Model):
    name = models.CharField(max_length=35, verbose_name="name")
    last_name = models.CharField(max_length=35, verbose_name="last_name", **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='email')
    comment = models.TextField(verbose_name='comment', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name="client")

    def __str__(self):
        return f" {self.name} {self.email}"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"


class Mailing(models.Model):
    DAY = 'ежедневно'
    WEEK = 'раз в неделю'
    MONTH = 'раз в месяц'
    CREATE = 'создана'
    START = 'запущена'
    STOP = 'завершена'
    CHOICE_PERIOD = [
        (DAY, "Раз в день"),
        (WEEK, "Раз в неделю"),
        (MONTH, "Раз в месяц"),
    ]
    CHOICE_STATUS = [
        (STOP, "Завершена"),
        (CREATE, "Создана"),
        (START, "Запущена"),
    ]

    name = models.CharField(max_length=50, verbose_name="Тема рассылки")
    message = models.TextField(verbose_name="Сообщение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создана")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Изменена")
    clients = models.ManyToManyField(Client, related_name="clients", verbose_name="Клиенты")
    start_mail = models.DateTimeField(default=timezone.now, verbose_name="Начало рассылки")
    stop_mail = models.DateTimeField(default=(timezone.now() + timezone.timedelta(days=1)),
                                     verbose_name="Конец рассылки")
    period_mail = models.CharField(
        max_length=100,
        choices=CHOICE_PERIOD,
        default=DAY,
        verbose_name="Периодичность")
    status_mail = models.CharField(max_length=100, choices=CHOICE_STATUS, default=CREATE, verbose_name="Статус")
    next_send_time = models.DateTimeField(verbose_name='Время следующей отправки', **NULLABLE)
    last_send_at = models.DateTimeField(null=True, verbose_name="Последняя рассылка")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"{self.name} ({self.last_send_at}) {self.owner}"

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Log(models.Model):
    SUCCESS = 'Успешно'
    FAIL = 'Неуспешно'
    STATUS_VARIANTS = [
        (SUCCESS, 'Успешно'),
        (FAIL, 'Неуспешно'),
    ]

    time = models.DateTimeField(
        verbose_name="Дата и время попытки отправки", auto_now_add=True
    )
    status = models.CharField(max_length=50, choices=STATUS_VARIANTS, verbose_name='Cтатус рассылки')
    server_response = models.CharField(
        max_length=150, verbose_name="Ответ сервера почтового сервиса", **NULLABLE
    )
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Рассылка")

    def __str__(self):
        return f"{self.mailing} {self.time} {self.status} {self.server_response}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    company = models.CharField(max_length=35, verbose_name='company', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='phone', **NULLABLE)
    avatar = models.ImageField(upload_to="image/", **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"
        permissions = [
            ('deactivate_user', 'Can deactivate user'),
            ('view_all_users', 'Can view all users'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import HiddenInput, ModelForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "first_name", "last_name", "phone", "avatar", "company"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = HiddenInput()


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["is_active"]

users/views.py
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserProfileForm, UserForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        user.token = token
        user.save()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение регистрации",
            message=f"Добро пожаловать на сайт! Для подтверждения регистрации перейди по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class PasswordResetView(View):
    form_class = PasswordResetForm
    template_name = "users/password_reset.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            try:
                user = User.objects.get(email=email)
                new_password = User.objects.make_random_password()
                user.password = make_password(new_password)
                user.save()

                send_mail(
                    subject="Восстановление пароля",
                    message=f"Ваш новый пароль: {new_password}",
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[email],
                )
                return redirect(reverse("users:login"))
            except User.DoesNotExist:
                form.add_error("email", "Пользователь с таким email не найден")
        return render(request, self.template_name, {"form": form})


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile.html"
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    permission_required = "users.view_all_users"


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    permission_required = "users.deactivate_user"
    success_url = reverse_lazy("users:user_list")

users/templates/users/login.html
{% extends 'emailservice/base.html'%}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="conteiner">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-titel">
                            Вход
                        </h3>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p}}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Войти
                        </button>
                    </div>
                </div>
                <a href="#" >Востановить пароль</a>
            </div>
        </div>
    </div>
</form>>
{% endblock %}

users/templates/users/password_reset.html
{% extends "emailservice/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm bg-light" style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                            <h2>Восстановление пароля</h2>
                    </div>
                    <div class="card-body py-3 flex-grow-1 ms-2">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary rounded-pill">
                                    Восстановить
                            </button>
                            <a class="btn btn-outline-secondary rounded-pill" href="{% url 'users:login' %}"
                               role="button">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends "emailservice/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm bg-light" style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                            <h2>Восстановление пароля</h2>
                    </div>
                    <div class="card-body py-3 flex-grow-1 ms-2">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary rounded-pill">
                                    Восстановить
                            </button>
                            <a class="btn btn-outline-secondary rounded-pill" href="{% url 'users:login' %}"
                               role="button">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
 {% extends "emailservice/base.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card shadow-sm " style="border-radius: 30px;">
                    <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                        <h2>Регистрация</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">Зарегистрироваться</button>
                            <a class="btn btn-outline-secondary" href="{% url 'main:client_list' %}"
                               role="button">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends "emailservice/base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow-sm bg-light" style="border-radius: 30px;">
                <div class="card-header bg-primary text-white text-center" style="border-radius: 30px 30px 0 0;">
                    {% if object %}
                        <h2>Редактирование информации пользователя</h2>
                    {% else %}
                        <h2>Создание пользователя</h2>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success rounded-pill" type="submit">Сохранить</button>
                        <a class="btn btn-secondary rounded-pill" href="{% url 'users:user_list' %}"
                           role="button">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends "emailservice/base.html" %}
{% load static %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                {% for user in object_list %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-header">
                                <h5><small>Активность: </small>{{ user.is_active }}</h5>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    Email: {{ user.email }}
                                </li>
                                <li class="list-group-item">
                                    Телефон: {{ user.phone }}
                                </li>
                                <li class="list-group-item">
                                    <div class="btn-group text-center">
                                        <a class="btn btn-outline-secondary btn-circle"
                                           href="{% url 'users:user_update' user.pk %}"
                                           role="button" title="Изменить">
                                            <img src="{% static 'crud_icons/edit.png' %}" alt="Изменить"
                                                 class="btn-icon">
                                        </a>

{#                                        <a class="btn btn-outline-secondary btn-circle btn-delete"#}
{#                                           href="{% url 'main:client_delete' user.pk %}"#}
{#                                           role="button" title="Удалить">#}
{#                                            <img src="{% static 'crud_icons/delete.png' %}" alt="Удалить"#}
{#                                                 class="btn-icon">#}
{#                                        </a>#}
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}